version: '3'

services:
  php:
    container_name: ${CONTAINER_PHP_NAME}
    image: php:fpm-alpine
    restart: unless-stopped
    volumes:
      - ${CODE_PATH}:/code
      - ${PHP_LOG_CONF_PATH}:/usr/local/etc/php-fpm.d/zz-log.conf

  web:
    depends_on:
      - php
    container_name: ${CONTAINER_WEB_NAME}
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${CODE_PATH}:/code
      - ${SITE_CONF_PATH}:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
  default:
    external:
      name: ${NETWORK}
